id = "atom-one-light-theme"
name = "Atom One Light Theme"
version = "0.1.0"
schema_version = 1
authors = ["Alexey Vlasov <sketchrhc@yandex.ru>""]
description = "Atom One Light theme ported from the VS Code theme."
repository = "https://github.com/sknsdev/onelight-zed"
